### ISSUE TITLE
Adding Arabic Support

### ISSUE THREAD

**Issue by Digital-Slayer** [jyaif/ppl-i18n#19]
Hi Jean,

I am a fan of your work, and I would like to add an arabic translation to PewPew Live. Just show me the steps, how feasible it is and i'll get to work.

**Comment by jyaif** [comment]
Hi,
Thanks for the offer!
Arabic is actually one of the languages that I don't plan on supporting right now because it requires an enormous amount of work.
PewPew draws all the text itself, and the rules for properly drawing Arabic are a little bit complicated.

Sorry about that! One day I hope I'll have time to work on that.

**Comment by Digital-Slayer** [comment]
Well, it was worth the try.
Thanks anyway.
