### ISSUE TITLE
Repo Moderators?

### ISSUE THREAD

**Issue by SKPG-Tech** [jyaif/ppl-i18n#37]
Should someone moderate this repo, because there are a lot of people that want to translate and you JF, can't keep up with them, I got this idea since you said you would add a translation file, but you didn't, we know you are busy so I wish to remove some work.

Moderators could:
- Make translation files.
- Merge good PRs.
- Answer to Issues and Questions.
- Regenerate readme.md file.

edit:

- contributors.json editing.

And more if you'd like to.

**Comment by jyaif** [comment]
Okay, we can try this out. I'm going to invite you as a collaborator to this repo.

Here are a couple of things to know:
* Before merging translation files, translate any suspicious translations: we don't want people to insert offensive terms.
* For new languages, create the new language file from `template.po. The 3 letter name of the language file is in ISO 639-2 ( https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes ). The python file also need some editing.
*  Only accept languages that don't require hundreds of new characters or have ligature requirements. This rules out CJK and arabic, unfortunately. For CJK, maybe someday I'll write an automatic character generator.
* Languages that require many new characters (e.g. vietnamese, hebrew) will require a lot of work from me. Not only will the characters need to be created, but there is also some refactoring needed to prevent the game from having to load all characters at start up.
* General coding style: in lists, items are usually in alphabetical order. An exception is the list of contributors for a language in contributors.json, where the order is temporal.
* I occasionally add new strings. Merging an old pull request *after* I added new strings will result in conflicts. They may be complicated to resolve, which is why I encourage people to do pull requests often, rather than do a single enormous pull requests that takes days to write.

**Comment by jyaif** [comment]
One more very important thing:
When merging pull request, **it is vital to choose "rebase and merge"**.
![image](https://user-images.githubusercontent.com/251239/104235519-63e77a80-5455-11eb-9eff-7b45fca7670d.png)

**Comment by SKPG-Tech** [comment]
Oh, Great Thanks, well see how this will go

**Comment by SKPG-Tech** [comment]
Should we close this issue?
